version: '3.7'
services:
  stacks-blockchain:
    image: "hirosystems/stacks-api-e2e:stacks2.4-f930deb"
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: host.docker.internal:3700
      BLOCKSTACK_USE_TEST_GENESIS_CHAINSTATE: 1
      NOP_BLOCKSTACK_DEBUG: 1
    ports:
      - "20443:20443"
      - "20444:20444"
    volumes:
      - ../stacks-blockchain/:/app/config
      - ../stacks-blockchain/.chaindata:/tmp/stacks-blockchain-data
    extra_hosts:
      - "host.docker.internal:host-gateway" # fixes `host.docker.internal` on linux hosts
