name: gh-pages

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install client deps
        run: npm install
        working-directory: client

      - name: Generate client docs
        run: npm run generate:docs
        working-directory: client

      - name: Install deps
        run: npm install
        working-directory: docs

      - name: Generate and deploy gh-pages
        run: npm run generate:types && npm run generate:docs
        working-directory: docs

      - name: Publish test coverage report
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs/.tmp
