[node]
name = "helium-node"
rpc_bind = "0.0.0.0:20443"
# working_dir = "/tmp/stacks-blockchain-data"

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 1000

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000

[[mstx_balance]]
address = "STF9B75ADQAVXQHNEQ6KGHXTG7JP305J2GRWF3A2"
# private = ce109fee08860bb16337c76647dcbc02df0c06b455dd69bcf30af74d4eedd19301
amount = 10000000000000000

[[mstx_balance]]
address = "ST18MDW2PDTBSCR1ACXYRJP2JX70FWNM6YY2VX4SS"
# private: 08c14a1eada0dd42b667b40f59f7c8dedb12113613448dc04980aea20b268ddb01
amount = 10000000000000000
